apiVersion: v1
kind: ConfigMap
metadata:
  name: datahub-config
  namespace: datahub
  labels:
    app.kubernetes.io/name: haskell-datahub
    app.kubernetes.io/part-of: haskell-datahub
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: datahub
  POSTGRES_USER: datahub

  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT: "8123"
  CLICKHOUSE_DB: datahub_analytics
  CLICKHOUSE_USER: datahub

  S3_HOST: minio
  S3_PORT: "9000"
  S3_SECURE: "false"
  S3_ACCESS_KEY: datahub
  S3_BUCKET: datahub-files

  GITHUB_API_BASE_URL: https://api.github.com
  GITHUB_API_VERSION: "2026-03-10"

  MINIO_ROOT_USER: datahub